language: ruby
sudo: false
cache: bundler

before_install:
  - gem install bundler

script: bundle exec rake

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 2.3.8
      script: bundle exec rubocop
